# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'i-weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for i-weather
pod 'Alamofire', '~> 5.2'
 pod 'IQKeyboardManagerSwift'

end
